config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#main'

  resources :sessions, only: [:index, :show, :create, :destroy]
  resources :records, only: [:index, :show, :new, :create, :destroy]

  get 'scrambles', to: 'scrambles#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :session

  validates :time, presence: true

  def display_time
    # format('%02d:%02d', ((time / 60) % 60), (time % 60))
    # time.to_s.reverse.scan(/.{1,2}/).join('.').reverse

    msec = (time % 1000).to_s.rjust(3, '0')[0, 2]
    sec = ((time / 1000) % 60).to_s
    min = ((time / 1000 / 60) % 60).to_s

    sec = sec.rjust(2, '0') if min != '0'

    chrono = [sec, msec].join('.')
    chrono = (min + ':' + chrono) if min != '0'

    chrono
  end
end

app/models/session.rb
class Session < ApplicationRecord
  has_many :records, dependent: :destroy

  enum category: { _333: 0, _222: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_browser_session

  def main
    @sessions = Session.all
  end

  private

  def set_browser_session
    if cookies[:browser_session]
      @browser_session = cookies[:browser_session]
    else
      loop do
        token = SecureRandom.hex(16)
        next if Session.exists?(browser_session: token)

        (@browser_session = token) && break
      end

      cookies[:browser_session] = @browser_session
    end
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  include ActionView::RecordIdentifier

  def show
    @record = Record.find(params[:id])
    @index = @record.session.records.order(created_at: :asc).pluck(:id).index(@record.id) + 1
  end

  def new
    @session = Session.find(params[:session_id]) if params[:session_id].present?
    @record = Record.new
  end

  def create
    @record = Record.create!(record_params)
    @times = @record.session.records.order(created_at: :desc).limit(12).map(&:time)

    respond_to do |format|
      format.turbo_stream do
        render(turbo_stream: turbo_stream.prepend('records-table', partial: 'records/record',
          locals: { record: @record, times: @times }))
      end
      # format.html { redirect_to(new_record_path(session_id: record_params[:session_id])) }
    end
  end

  def destroy
    record = Record.find(params[:id])
    record.destroy!

    redirect_to(sessions_path(selected_session_id: record.session_id))
  end

  private

  def record_params
    params.require(:record).permit(:session_id, :time, :scramble)
  end
end

app/controllers/scrambles_controller.rb
class ScramblesController < ApplicationController
  def show
    @category = category
    @scramble = Scrambler.new.send(@category)
  end

  private

  def category
    return Scrambler::CATEGORIES.first if params[:category].blank?

    raise 'Invalid Category' if Scrambler::CATEGORIES.exclude?(params[:category])

    params[:category]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_browser_session
  before_action :set_sessions, only: [:index]
  before_action :set_selected_session, only: [:index]

  def index
    @records = @selected_session.records.order(created_at: :asc)
    @times = @records.map(&:time).reverse
  end

  def show
    @session = Session.find(params[:id])
    @records = @session.records
  end

  def create
    @session = Session.create!(browser_session: @browser_session)

    redirect_to(sessions_path(selected_session_id: @session.id))
  end

  def destroy
    session = Session.find(params[:id])
    session.destroy!

    redirect_to(sessions_path)
  end

  private

  def set_sessions
    @sessions ||= Session.where(browser_session: @browser_session).order(created_at: :asc)
  end

  def set_selected_session
    @selected_session ||= if params[:selected_session_id].present?
      @sessions.find(params[:selected_session_id])
    else
      @sessions.first
    end

    @selected_session ||= Session.create!(browser_session: @browser_session)
  end

  def set_browser_session
    @browser_session = cookies[:browser_session]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dashboard/main.html.erb
<div id="dashboard-container"
      data-controller="dashboard"
      data-action="keydown@window->dashboard#keydown keyup@window->dashboard#keyup"
      class="flex flex-1 flex-col flex-nowrap justify-between min-h-screen h-screen max-h-screen bg-white"
      data-dashboard-standby-class="text-gray-200"
      data-dashboard-ready-class="text-red-700"
      data-dashboard-set-class="text-green-600"
      data-dashboard-running-class="text-gray-200"
>
  <div id="header" class="flex flex-none h-[100px] border-b-[2px] border-gray-400 bg-slate-900">
    <div id="logo-container" class="mx-[50px] my-[4px]">
      <!--<img src="<%= asset_path('logo.png') %>" width="300">-->
      <span class="font-bold text-[60px] text-gray-100 antialiased">A-Timer</span>
    </div>
  </div>

  <div id="main-container" class="flex flex-1 flex-nowrap flex-row justify-start items-stretch min-h-0 bg-slate-900">
    <div id="sessions-container" class="flex flex-col flex-nowrap justify-end min-w-[400px] max-w-[400px] w-fit max-h-full my-[10px] mx-[10px] border-[1px] border-gray-400">
      <turbo-frame id="sessions-frame" src=<%= "/sessions"%> data-dashboard-target="sessionsFrame" class="flex flex-1 flex-col flex-nowrap justify-start overflow-y-auto">
      </turbo-frame>
    </div>

    <div id="timer-container" class="flex flex-1 flex-col flex-wrap justify-center content-center">
      <turbo-frame id="scramble-frame" src=<%= "/scrambles"%> data-dashboard-target="scrambleFrame" class="flex flex-col flex-wrap justify-center content-center">
      </turbo-frame>
    
      <turbo-frame id="record-frame" src=<%= "/records/new"%> data-dashboard-target="recordFrame" class="flex flex-1 flex-col flex-wrap justify-center content-center">
      </turbo-frame>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ATimer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex min-w-screen min-h-screen h-screen">
    <main class="flex w-full min-h-screen max-h-screen">
      <%= yield %>
    </main>
  </body>
</html>

app/views/records/_record.html.erb
<div id="<%= dom_id(record) %>"class="grid grip-rows-1 grid-cols-5 gap-0 w-[360px]>">
  <div class="text-center box-border border-t border-b border-l border-gray-400"><%= record.session.records.count %></div>
  <div class="text-center box-border border-t border-b border-l border-gray-400"><%= record.display_time %></div>
  <div class="text-center box-border border-t border-b border-l border-gray-400"><%= avg5(times[0..4]) %></div>
  <div class="text-center box-border border-t border-b border-l border-gray-400"><%= avg12(times) %></div>
  <div class="text-center box-border border border-gray-400 peer overflow-x-visible">
    <%= button_to record, :method => :get do %>
      <%= fa_icon "info-circle" %>
    <% end %>
  </div>
</div>

app/views/records/_records_table.html.erb
<div class="flex flex-1 flex-col w-fit overflow-y-hidden">
  <div id="records-table" class="overflow-y-auto w-[360px]">
    <% records.reverse_each.with_index do |record, index| %>
      <div id="<%= dom_id(record) %>"class="grid grip-rows-1 grid-cols-5 gap-0 w-[360px]> min-w-[360px]>">
        <div class="text-center box-border border-t border-b border-l border-gray-400"><%= records_count - index %></div>
        <div class="text-center box-border border-t border-b border-l border-gray-400"><%= record.display_time %></div>
        <div class="text-center box-border border-t border-b border-l border-gray-400"><%= avg5(times[index..(index + 4)]) %></div>
        <div class="text-center box-border border-t border-b border-l border-gray-400"><%= avg12(times[index..(index + 11)]) %></div>
        <div class="text-center box-border border border-gray-400 peer overflow-x-visible">
          <%= button_to record, :method => :get, class: 'w-full' do %>
            <%= fa_icon "info-circle" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/records/new.html.erb
<turbo-frame id="record-frame" data-dashboard-target="recordFrame" class="flex flex-1 flex-col flex-wrap justify-start content-center">
  <div class="flex justify-center w-full">
    <div class="font-orbitron text-[160px] tabular-nums" data-dashboard-target="timerContainer" data-timer-status="standby">
      <span id="sec">0</span>.<span id="msec">00</span>
    </div>
  </div>

  <%= form_with(model: @record, url: records_path, method: :post, local: true, data: {"dashboard-target": "recordForm", "action": "dashboard#beforeSubmitRecord turbo:submit-end->dashboard#afterSubmitRecord"}) do |f| %>
    <%= f.hidden_field :time, class: "text-[40px]", data: {"dashboard-target": "recordTimeInput"} %>
    <%= f.hidden_field :session_id, value: params[:session_id], data: {"dashboard-target": "recordSessionIdInput"} %>
    <%= f.hidden_field :scramble, value: '', data: {"dashboard-target": "recordScrambleInput"} %>
  <% end %>
</turbo-frame>

app/views/records/show.html.erb
<turbo-frame id="sessions-frame">
  <div class="my-[10px] text-center">Record #<%= @index %></div>

  <div class="flex flex-1 flex-col flex-nowrap overflow-y-auto">
    <div class="grid grip-rows-1 grid-cols-2 gap-0">
      <div class="text-center m-[10px]">Time:</div>
      <div class="text-center m-[10px]"><%= @record.display_time %></div>
    </div>

    <div class="grid grip-rows-1 grid-cols-2 gap-0">
      <div class="text-center m-[10px]">Scramble:</div>
      <div class="text-center m-[10px]"><%= @record.scramble %></div>
    </div>

    <div class="flex flex-col flex-nowrap justify-center">
      <div class="text-center m-[10px]">
        <%= button_to @record, :method => :delete, class: 'w-full' do %>
          <%= fa_icon "times", class: "fa-lg" %>
        <% end %>
      </div>
      <div class="text-center m-[10px]">
        <%= button_to sessions_path(selected_session_id: @record.session_id), :method => :get, class: 'w-full' do %>
          <%= fa_icon "arrow-left", class: "fa-lg" %>
        <% end %>
      </div>
    </div>
  </div>
</turbo-frame>

app/views/scrambles/_scramble.html.erb
<turbo-frame id="scramble-frame">
  <div class="flex flex-row flex-nowrap justify-center w-full">
    <select name="scramble-category-select" id="scramble-category-select" data-action="change->dashboard#changeScrambleCategory" data-dashboard-target="scrambleCategorySelect" class="mt-[20px] mb-[10px] mx-[20px] py-[0px] border-gray-400 bg-slate-900">
      <% Scrambler::CATEGORIES.each do |c| %>
        <option value="<%= c %>" <%= "selected" if c == category %>><%= c.titleize %></option>
      <% end %>
    </select>

    <a href="scrambles?category=<%= @category %>" data-dashboard-target="newScrambleAnchor" class="flex flex-col justify-center text-center underline h-fit w-[40px] mt-[20px] hover:bg-gray-200 hover:text-slate-900">new</a>
  </div>

  <div class="flex justify-center font-orbitron text-[36px] space-[20px]" data-dashboard-target="scrambleContainer">
    <%= scramble.html_safe %>
  </div>
</turbo-frame>

app/views/scrambles/show.html.erb
<%= render partial: 'scramble', locals: { scramble: @scramble, category: @category } %>